import { Body, Query, Vector, type Body as MatterBody } from 'matter-js';
import { GAME_CONFIG as C } from './config';
import type { PhysicsWorld } from './physics';
import type { CanvasRenderer } from './renderer';
export class PointerInput {
  private pointerId: number | null=null; private body: MatterBody | null=null; private offset={x:0,y:0}; private samples: {p:Matter.Vector;t:number}[]=[];
  private downClient={x:0,y:0}; private moved=false; private startVelocity={x:0,y:0}; private lastTap:{id:number;x:number;y:number;t:number}|null=null;
  constructor(private canvas: HTMLCanvasElement, private renderer: CanvasRenderer, private world: PhysicsWorld) { canvas.addEventListener('pointerdown',this.down); canvas.addEventListener('pointermove',this.move); canvas.addEventListener('pointerup',this.up); canvas.addEventListener('pointercancel',this.up); }
  private down=(e:PointerEvent) => { const p=this.renderer.screenToWorld(e.clientX,e.clientY), bodies=[...this.world.balls.values()].map(b=>b.body), body=Query.point(bodies,p)[0]; if(!body)return; e.preventDefault(); this.pointerId=e.pointerId; this.body=body; this.offset=Vector.sub(body.position,p); this.samples=[{p,t:performance.now()}]; this.downClient={x:e.clientX,y:e.clientY};this.moved=false;this.startVelocity={...body.velocity};this.canvas.setPointerCapture(e.pointerId); Body.setVelocity(body,{x:0,y:0}); };
  private move=(e:PointerEvent) => { if(e.pointerId!==this.pointerId||!this.body)return; e.preventDefault(); if(Math.hypot(e.clientX-this.downClient.x,e.clientY-this.downClient.y)>C.TAP_MOVE_TOLERANCE_PX)this.moved=true; const p=this.renderer.screenToWorld(e.clientX,e.clientY), raw=Vector.add(p,this.offset), radius=this.body.circleRadius??0, target={x:Math.max(radius,Math.min(C.FIELD_SIZE-radius,raw.x)),y:Math.max(radius,Math.min(C.FIELD_SIZE-radius,raw.y))}; Body.setPosition(this.body,target); Body.setVelocity(this.body,{x:0,y:0}); const now=performance.now(); this.samples.push({p:target,t:now}); this.samples=this.samples.filter(s=>now-s.t<100); };
  private up=(e:PointerEvent) => { if(e.pointerId!==this.pointerId||!this.body)return; e.preventDefault(); const body=this.body,last=this.samples.at(-1),first=this.samples[0],now=performance.now(); if(this.moved&&last&&first&&last.t>first.t) Body.setVelocity(body,Vector.mult(Vector.sub(last.p,first.p),C.DRAG_THROW_SCALE*1000/(last.t-first.t))); else Body.setVelocity(body,this.startVelocity); const id=Number(body.label.slice(5)); if(!this.moved){const prior=this.lastTap;if(prior&&prior.id===id&&now-prior.t<=C.DOUBLE_TAP_MS&&Math.hypot(e.clientX-prior.x,e.clientY-prior.y)<=C.DOUBLE_TAP_DISTANCE_PX){const direction=Vector.magnitude(body.velocity)>0?Vector.normalise(body.velocity):{x:1,y:0};this.world.splitBall(id,direction);this.lastTap=null;}else this.lastTap={id,x:e.clientX,y:e.clientY,t:now};}else this.lastTap=null; this.pointerId=null; this.body=null; this.samples=[]; };
}
